// src/components/TheFooter.svelte
<style>
  footer {
    text-align: center;
    background: var(--accent-darker);
    padding: 2em 0.5em;
    font-size: 0.8em;
    color: #fff;
  }

  footer a {
    color: #cecece;
  }

  footer a:hover {
    color: #fff;
  }
</style>

<footer>
  <div class="mid">
    Copyright (c) 2019-present
    <a href="https://github.com/fenny" target="_blank">Fenny</a>
    and
    <a
      href="https://github.com/gofiber/fiber/graphs/contributors"
      target="blank">
      Contributors
    </a>
    . Fiber is free and open-source software licensed under the
    <a
      href="https://github.com/gofiber/fiber/blob/master/LICENSE"
      target="_blank">
      MIT License
    </a>
    . Official logo was created by
    <a href="https://github.com/koddr" target="_blank">Vic Shóstak</a>
    and distributed under
    <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">
      Creative Commons
    </a>
    license (CC BY-SA 4.0 International). Fiber Documentation is hosted by
    <a href="https://gitbook.com" target="_blank">GitBook.com</a>
    . Website by
    <a href="https://github.com/jozsefsallai" target="_blank">József Sallai</a>
    .
  </div>
</footer>

// components/common/TheFooter.tsx
import styles from './TheFooter.module.scss';
import { Component } from 'react';
import { GenericLink } from 'typings';

class FooterLink extends Component<GenericLink> {
  render() {
    return (
      <a href={this.props.url} target="_blank">
        {this.props.text}
      </a>
    );
  }
}

const Links = {
  Fenny: () => <FooterLink url="https://github.com/fenny" text="Fenny" />,
  Contributors: () => (
    <FooterLink
      url="https://github.com/gofiber/fiber/graphs/contributors"
      text="Contributors"
    />
  ),
  ProjectLicense: () => (
    <FooterLink
      url="https://github.com/gofiber/fiber/blob/master/LICENSE"
      text="MIT License"
    />
  ),
  LogoDesigner: () => (
    <FooterLink url="https://github.com/koddr" text="Vic Shóstak" />
  ),
  LogoLicense: () => (
    <FooterLink
      url="https://creativecommons.org/licenses/by-sa/4.0"
      text="Creative Commons"
    />
  ),
  GitBook: () => <FooterLink url="https://gitbook.com" text="GitBook.com" />,
  WebsiteBy: () => <FooterLink url="https://sallai.me" text="József Sallai" />,
};

class TheFooter extends Component {
  render() {
    return (
      <footer className={styles.mainFooter}>
        <div className="mid">
          Copyright (c) 2019-present <Links.Fenny /> and <Links.Contributors />.
          Fiber is free and open-source software licensed under the{' '}
          <Links.ProjectLicense />. Official logo was created by{' '}
          <Links.LogoDesigner /> and distributed under the <Links.LogoLicense />{' '}
          license (CC BY-SA 4.0 International). Fiber Documentation is hosted by{' '}
          <Links.GitBook />. Website by <Links.WebsiteBy />.
        </div>
      </footer>
    );
  }
}

export default TheFooter;
