// src/components/TheHeader.svelte
<script>
  import Icon from "fa-svelte";
  import { faBars } from "@fortawesome/free-solid-svg-icons";

  let opened = false;

  function toggleHamburger() {
    opened = !opened;
  }
</script>

<style>
  header {
    padding: 1em;
  }

  header .header-mid {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  header .header-mid .header-left .logo {
    width: 110px;
  }

  nav a {
    color: #000;
    display: inline-block;
    padding: 0.4em 1em;
    margin-right: 0.3em;
    border-radius: 3px;
  }

  nav a:last-child {
    margin-right: 0;
  }

  nav a:hover {
    background: var(--accent);
    color: #fff;
    text-decoration: none;
  }

  .hamburger-opener {
    display: none;
    position: absolute;
    top: 0;
    right: 0;
  }

  .hamburger-opener a {
    font-size: 2em;
    color: #222;
    display: block;
    padding: 0.4em;
  }

  @media only screen and (max-width: 920px) {
    header {
      padding: 0;
    }

    header .header-mid {
      display: block;
      padding: 0;
    }

    header .header-left {
      padding: 0.7em;
    }

    .hamburger-opener {
      display: block;
    }

    nav {
      border-top: 1px solid #e6ecf1;
      background: #f5f7f9;
      display: none;
    }

    nav.opened {
      display: block;
    }

    nav a {
      display: block;

      border-radius: 0;
      border-bottom: 1px solid #e6ecf1;
    }
  }
</style>

<header>
  <div class="mid header-mid">
    <div class="header-left">
      <a href="/">
        <img src="/assets/images/logo.svg" alt="Fiber" class="logo" />
      </a>
    </div>
    <div class="header-right">
      <nav class={opened ? 'opened' : undefined}>
        <a href="https://docs.gofiber.io">📖 Docs</a>
        <a href="https://github.com/gofiber/recipes">🍳 Examples</a>
        <a href="https://github.com/gofiber/fiber">📝 GitHub</a>
        <a href="https://www.buymeacoffee.com/fenny">☕ Buy a Coffee</a>
        <a href="https://gofiber.io/discord">💬 Discord</a>
      </nav>
    </div>
  </div>

  <div class="hamburger-opener">
    <a href="javascript:;" on:click={toggleHamburger}>
      <Icon icon={faBars} />
    </a>
  </div>
</header>

// components/common/TheHeader.tsx
import styles from './TheHeader.module.scss';

import { Component } from 'react';
import { GenericLink } from 'typings';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars } from '@fortawesome/free-solid-svg-icons';

interface TheHeaderState {
  opened: boolean;
}

class TheHeader extends Component<{}, TheHeaderState> {
  constructor(props) {
    super(props);
    this.state = {
      opened: false,
    };

    this.toggleHamburger = this.toggleHamburger.bind(this);
  }

  private readonly links: GenericLink[] = [
    { url: 'https://docs.gofiber.io', text: '📖 Docs' },
    { url: 'https://github.com/gofiber/recipes', text: '🍳 Examples' },
    { url: 'https://github.com/gofiber/fiber', text: '📝 GitHub' },
    { url: 'https://www.buymeacoffee.com/fenny', text: '☕ Buy a Coffee' },
    { url: '/discord', text: '💬 Discord' },
  ];

  private toggleHamburger() {
    this.setState({
      opened: !this.state.opened,
    });
  }

  render() {
    return (
      <header className={styles.header}>
        <div className={`mid ${styles.headerMid}`}>
          <div className={styles.headerLeft}>
            <a href="/">
              <img
                src="/assets/images/logo.svg"
                alt="Fiber"
                className={styles.logo}
              />
            </a>
          </div>

          <div>
            <nav className={this.state.opened ? styles.opened : undefined}>
              {this.links.map((link, idx) => (
                <a href={link.url} key={idx}>
                  {link.text}
                </a>
              ))}
            </nav>
          </div>
        </div>

        <div className={styles.hamburgerOpener}>
          <a href="#" onClick={this.toggleHamburger}>
            <FontAwesomeIcon icon={faBars} />
          </a>
        </div>
      </header>
    );
  }
}

export default TheHeader;
