// components/blocks/MainBlock.tsx
import styles from './MainBlock.module.scss';
import { Component } from 'react';

import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import CodeBlock from '../windows/CodeBlock';
import BrowserWindow from '../windows/BrowserWindow';

const exampleCode = `package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.Get("/", func (c *fiber.Ctx) {
    c.Send("Hello, World!")
  })

  app.Listen(3000)
}`;

class MainBlock extends Component {
  render() {
    return (
      <div>
        <section className={`mid ${styles.mainBlock}`}>
          <h2 className={styles.largeText}>An Express-inspired web framework written in Go.</h2>
          <div className={styles.description}>
            Fiber is a Go web framework built on top of Fasthttp, the <strong>fastest</strong> HTTP
            engine for Go. It's designed to <strong>ease</strong> things up for fast development
            with <strong>zero memory allocation</strong> and <strong>performance</strong> in mind.
          </div>
        </section>

        <section className={`mid ${styles.mainExample}`}>
          <div className={styles.codeExampleWrapper}>
            <CodeBlock>{exampleCode}</CodeBlock>
          </div>

          <div className={styles.arrowContainer}>
            <FontAwesomeIcon icon={faArrowRight} />
          </div>

          <div className={styles.result}>
            <BrowserWindow url="http://localhost:3000">
              <pre>
                Hello, World!
              </pre>
            </BrowserWindow>
          </div>
        </section>

        <section className="emphasized-button">
          <div className="mid">
            <a href="https://docs.gofiber.io">
              <span>Get Started</span>
              <FontAwesomeIcon icon={faArrowRight} />
            </a>
            <div className={styles.orScroll}>...or scroll to learn more.</div>
          </div>
        </section>
      </div>
    );
  }
}

export default MainBlock;

// src/components/blocks/MainBlock.svelte
<script>
  import CodeBlock from '../CodeBlock.svelte';
  import BrowserWindow from '../BrowserWindow.svelte';

  import Icon from 'fa-svelte';
  import { faArrowRight } from '@fortawesome/free-solid-svg-icons';

  const exampleCode = `// server.go

package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.get("/", func (c *fiber.Ctx) {
    c.Send("Hello, World!")
  })

  app.Listen(3000)
}`;
</script>

<section class="mid main-block">
  <h2 class="large-text">An Express-inspired web framework written in Go.</h2>
  <div class="description">
    Fiber is a Go web framework built on top of Fasthttp, the <strong>fastest</strong>
    HTTP engine for Go. It's designed to <strong>ease</strong> things up for fast
    development with <strong>zero memory allocation</strong> and <strong>performance</strong>
    in mind.
  </div>
</section>

<section class="mid main-example">
  <div class="code-example-wrapper">
    <CodeBlock>
      {exampleCode}
    </CodeBlock>
  </div>

  <div class="arrow-container">
    <Icon icon={faArrowRight} />
  </div>

  <div class="result">
    <BrowserWindow>
      <pre style="word-wrap: break-word; white-space: pre-wrap;">
        Hello, World!
      </pre>
    </BrowserWindow>
  </div>
</section>

<section class="emphasized-button">
  <div class="mid">
    <a href="https://docs.gofiber.io">
      <span>Get Started</span>
      <Icon icon={faArrowRight} />
    </a>
    <div class="or-scroll">...or scroll to learn more.</div>
  </div>
</section>

<style>
  .main-block {
    text-align: center;
    padding: 5em 1em;
  }

  .main-block .large-text {
    font-weight: 800;
    font-size: 3em;
    margin: 0;
  }

  .main-block .description {
    font-size: 1.2em;
    width: 80%;
    margin: 0 auto;
  }

  .main-example {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 3em;
  }

  .main-example .code-example-wrapper, .main-example .result {
    width: 40%;
  }

  .main-example .arrow-container {
    color: #676767;
    font-size: 2.2em;
  }

  .or-scroll {
    margin-top: 1em;
    color: #777;
  }
</style>
