// src/components/CodeBlock.svelte
<div class="code-block">
  <div class="window dark">
    <div class="titlebar">
      <div class="titlebar-buttons">
        <div class="titlebar-button close"></div>
        <div class="titlebar-button maximize"></div>
        <div class="titlebar-button minimize"></div>
      </div>
    </div>
    <div class="window-content">
      <pre>
        <code class="go">
          <slot></slot>
        </code>
      </pre>
    </div>
  </div>
</div>

<style>
  pre code {
    background: #111;
    border-bottom-left-radius: 6px;
    border-bottom-right-radius: 6px;
    line-height: 1.2;
  }

  .window-content pre {
    margin: 0;
  }
</style>

// components/windows/CodeBlock.tsx
import styles from './CodeBlock.module.scss';
import { Component } from 'react';
import { findDOMNode } from 'react-dom';
import hljs from 'highlight.js';

class CodeBlock extends Component {
  componentDidMount() {
    hljs.highlightBlock(findDOMNode(this.refs.code));
  }

  render() {
    return (
      <div className="code-block">
        <div className="window dark">
          <div className="titlebar">
            <div className="titlebar-buttons">
              <div className="titlebar-button close"></div>
              <div className="titlebar-button maximize"></div>
              <div className="titlebar-button minimize"></div>
            </div>
          </div>

          <div className={`window-content ${styles.codeWindowContent}`}>
            <pre>
              <code className="go" ref="code">
                {this.props.children}
              </code>
            </pre>
          </div>
        </div>
      </div>
    );
  }
}

export default CodeBlock;
